//! Store: a directory.
//!
//! ```text
//! <root>/device_id          one line, regenerated by a full reset
//! <root>/provisioned.json   credentials + device token, absent until claimed
//! <root>/pending/<id>.jpg   the durable queue, same layout as the Pi's
//! ```
//!
//! Writes go to a dot-prefixed temporary file and are renamed into place, so a
//! power cut never leaves a half-written JPEG in the queue — the rule the Pi
//! device follows and the reason the queue can be trusted after a reset.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use chrono::Utc;
use daily_mirror_core::ports::{Provisioned, QueuedCapture, Store};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug)]
pub struct DirStore {
    root: PathBuf,
}

#[derive(Debug, Deserialize, Serialize)]
struct ProvisionedFile {
    ssid: String,
    psk: String,
    server_url: String,
    device_token: String,
    device_name: String,
}

impl DirStore {
    pub fn open(root: impl Into<PathBuf>) -> Result<Self> {
        let root = root.into();
        fs::create_dir_all(root.join("pending"))
            .with_context(|| format!("create the device store at {}", root.display()))?;
        Ok(Self { root })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    fn pending_dir(&self) -> PathBuf {
        self.root.join("pending")
    }

    fn queue_path(&self, capture_id: &str) -> Result<PathBuf> {
        if capture_id.is_empty()
            || !capture_id
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
        {
            return Err(anyhow!("unsafe capture id {capture_id:?}"));
        }
        Ok(self.pending_dir().join(format!("{capture_id}.jpg")))
    }

    /// The device id as an owned `String`, minting and persisting one on first
    /// use. Separate from the trait method so callers outside the runtime can
    /// read it without a `&mut` borrow dance.
    pub fn device_id_owned(&mut self) -> Result<String> {
        let path = self.root.join("device_id");
        if let Ok(existing) = fs::read_to_string(&path) {
            let existing = existing.trim().to_string();
            if !existing.is_empty() {
                return Ok(existing);
            }
        }
        let minted = format!("dm-{}", &Uuid::new_v4().simple().to_string()[..16]);
        write_atomic(&path, minted.as_bytes())?;
        Ok(minted)
    }
}

impl Store for DirStore {
    type Error = anyhow::Error;

    fn device_id(&mut self) -> Result<String> {
        self.device_id_owned()
    }

    fn load(&mut self) -> Result<Option<Provisioned>> {
        let path = self.root.join("provisioned.json");
        match fs::read(&path) {
            Ok(bytes) => {
                let file: ProvisionedFile = serde_json::from_slice(&bytes)
                    .with_context(|| format!("decode {}", path.display()))?;
                Ok(Some(Provisioned {
                    ssid: file.ssid,
                    psk: file.psk,
                    server_url: file.server_url,
                    device_token: file.device_token,
                    device_name: file.device_name,
                }))
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(error).with_context(|| format!("read {}", path.display())),
        }
    }

    fn save(&mut self, provisioned: &Provisioned) -> Result<()> {
        let file = ProvisionedFile {
            ssid: provisioned.ssid.clone(),
            psk: provisioned.psk.clone(),
            server_url: provisioned.server_url.clone(),
            device_token: provisioned.device_token.clone(),
            device_name: provisioned.device_name.clone(),
        };
        let json = serde_json::to_vec_pretty(&file)?;
        write_atomic(&self.root.join("provisioned.json"), &json)
    }

    fn next_capture_id(&mut self) -> Result<String> {
        // The Pi's scheme: sortable UTC stamp plus eight hex characters.
        let suffix = Uuid::new_v4().simple().to_string();
        Ok(format!(
            "{}-{}",
            Utc::now().format("%Y%m%dT%H%M%SZ"),
            &suffix[..8]
        ))
    }

    fn enqueue(&mut self, capture_id: &str, jpeg: &[u8]) -> Result<QueuedCapture> {
        let path = self.queue_path(capture_id)?;
        write_atomic(&path, jpeg)?;
        Ok(QueuedCapture {
            capture_id: capture_id.to_string(),
            bytes: jpeg.len() as u64,
        })
    }

    fn read(&mut self, capture_id: &str) -> Result<Vec<u8>> {
        let path = self.queue_path(capture_id)?;
        fs::read(&path).with_context(|| format!("read queued capture {}", path.display()))
    }

    fn pending(&mut self) -> Result<Vec<QueuedCapture>> {
        let mut pending = Vec::new();
        let entries = match fs::read_dir(self.pending_dir()) {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(pending),
            Err(error) => return Err(error.into()),
        };
        for entry in entries {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|value| value.to_str()) != Some("jpg") {
                continue;
            }
            let Some(capture_id) = path.file_stem().and_then(|value| value.to_str()) else {
                continue;
            };
            pending.push(QueuedCapture {
                capture_id: capture_id.to_string(),
                bytes: entry.metadata()?.len(),
            });
        }
        // Capture ids sort chronologically, so the queue drains oldest first.
        pending.sort_by(|left, right| left.capture_id.cmp(&right.capture_id));
        Ok(pending)
    }

    fn remove(&mut self, capture_id: &str) -> Result<()> {
        let path = self.queue_path(capture_id)?;
        match fs::remove_file(&path) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error).with_context(|| format!("remove {}", path.display())),
        }
    }

    fn erase_all(&mut self) -> Result<()> {
        if self.root.exists() {
            fs::remove_dir_all(&self.root)
                .with_context(|| format!("erase {}", self.root.display()))?;
        }
        fs::create_dir_all(self.pending_dir())?;
        // Minting a fresh device id is part of the reset: the server treats the
        // old row as released and the device claims into its new household as
        // an entirely new device.
        let _ = self.device_id_owned()?;
        Ok(())
    }
}

fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| anyhow!("{} has no parent directory", path.display()))?;
    fs::create_dir_all(parent)?;
    let name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| anyhow!("{} has no file name", path.display()))?;
    let temporary = parent.join(format!(".{name}.tmp"));
    fs::write(&temporary, bytes).with_context(|| format!("write {}", temporary.display()))?;
    fs::rename(&temporary, path).with_context(|| format!("commit {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_store() -> DirStore {
        let root = std::env::temp_dir().join(format!("dm-store-{}", Uuid::new_v4().simple()));
        DirStore::open(root).unwrap()
    }

    fn provisioned() -> Provisioned {
        Provisioned {
            ssid: "home".into(),
            psk: "secret".into(),
            server_url: "https://mirror.example".into(),
            device_token: "dt_1".into(),
            device_name: "Hallway".into(),
        }
    }

    #[test]
    fn device_id_is_stable_across_opens() {
        let mut store = temp_store();
        let first = store.device_id().unwrap();
        let mut reopened = DirStore::open(store.root()).unwrap();
        assert_eq!(reopened.device_id().unwrap(), first);
    }

    #[test]
    fn provisioned_state_round_trips() {
        let mut store = temp_store();
        assert!(store.load().unwrap().is_none());
        store.save(&provisioned()).unwrap();
        assert_eq!(store.load().unwrap(), Some(provisioned()));
    }

    #[test]
    fn queue_enqueues_reads_and_removes_in_order() {
        let mut store = temp_store();
        store
            .enqueue("20260101T000002Z-bbbbbbbb", b"second")
            .unwrap();
        let first = store
            .enqueue("20260101T000001Z-aaaaaaaa", b"first")
            .unwrap();
        assert_eq!(first.bytes, 5);

        let pending = store.pending().unwrap();
        assert_eq!(pending.len(), 2);
        assert_eq!(pending[0].capture_id, "20260101T000001Z-aaaaaaaa");
        assert_eq!(store.read(&pending[0].capture_id).unwrap(), b"first");

        store.remove(&pending[0].capture_id).unwrap();
        assert_eq!(store.pending().unwrap().len(), 1);
        // Removing twice is not an error; a retry may race with a drain.
        store.remove(&pending[0].capture_id).unwrap();
    }

    #[test]
    fn capture_ids_with_path_separators_are_refused() {
        let mut store = temp_store();
        assert!(store.enqueue("../escape", b"no").is_err());
        assert!(store.read("../../etc/passwd").is_err());
    }

    #[test]
    fn erase_all_clears_credentials_queue_and_device_id() {
        let mut store = temp_store();
        let original_id = store.device_id().unwrap();
        store.save(&provisioned()).unwrap();
        store.enqueue("20260101T000001Z-aaaaaaaa", b"jpeg").unwrap();

        store.erase_all().unwrap();

        assert!(store.load().unwrap().is_none());
        assert!(store.pending().unwrap().is_empty());
        assert_ne!(store.device_id().unwrap(), original_id);
    }

    #[test]
    fn capture_ids_are_sortable_and_safe() {
        let mut store = temp_store();
        let id = store.next_capture_id().unwrap();
        assert_eq!(id.len(), 25);
        assert!(
            id.bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
        );
    }
}
