/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletes the signed-in account, as App Review guideline 5.1.1(v) requires.
         * @description The session is revoked first so a half-finished delete can never leave a
         *     usable token pointing at a deleted account, and the browser cookie is
         *     expired on the way out.
         */
        delete: operations["deleteApiAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/faces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminFaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiAdminFaces"];
        trace?: never;
    };
    "/api/admin/faces/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAdminFacesSuggest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/faces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiAdminFacesById"];
        trace?: never;
    };
    "/api/admin/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminHouseholds"];
        put?: never;
        post: operations["postApiAdminHouseholds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/households/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiAdminHouseholdsById"];
        trace?: never;
    };
    "/api/admin/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminPeople"];
        put?: never;
        post: operations["postApiAdminPeople"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminPeopleByIdPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/native": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAuthLoginNative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/native/passkey/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAuthLoginNativePasskeyFinish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/native/passkey/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAuthLoginNativePasskeyStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAuthPasskeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-service signup. Disabled unless `DAILY_MIRROR_ALLOW_SIGNUP=1`, because
         *     every session can still read every household's photos.
         */
        post: operations["postApiAuthSignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's household devices. Session authenticated by `view_auth`. */
        get: operations["getApiDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem a claim token for a per-device bearer token.
         * @description Deliberately unauthenticated: the claim token is the credential, and the
         *     device has no session. 409 means the device already belongs to another
         *     household and was not released by a full reset.
         */
        post: operations["postApiDevicesClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/claim-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a single-use claim token bound to the signed-in user's household.
         * @description The app hands the token to a device over the local provisioning link; the
         *     device redeems it at `POST /api/devices/claim` within
         *     `CLAIM_TOKEN_TTL_SECONDS`.
         *
         *     An account with no household is refused with 409 rather than having one
         *     guessed for it, so a camera can never be paired into a stranger's home.
         */
        post: operations["postApiDevicesClaim-tokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiHousehold"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Renaming is an administrator action; members get 403. */
        patch: operations["patchApiHousehold"];
        trace?: never;
    };
    "/api/household/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiHouseholdPeople"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/people/{person_id}/enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiHouseholdPeopleByPerson_idEnrollment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/people/{person_id}/enrollment/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Session authenticated: the caller's own household decides who may be
         *     enrolled, so the device upload token plays no part here.
         */
        post: operations["postApiHouseholdPeopleByPerson_idEnrollmentUploads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/people/{person_id}/enrollment/uploads/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiHouseholdPeopleByPerson_idEnrollmentUploadsByPhoto_id"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiMaintenanceProcess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiMaintenanceReconcile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteApiPhotosById"];
        options?: never;
        head?: never;
        patch: operations["patchApiPhotosById"];
        trace?: never;
    };
    "/api/photos/{id}/faces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Face bounds and identities for one photograph, so viewers can label who
         *     the pipeline found without loading the admin dashboard.
         */
        get: operations["getApiPhotosByIdFaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{id}/flipbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putApiPhotosByIdFlipbook"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiUploads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminBounds: {
            /** Format: float */
            height: number;
            /** Format: float */
            width: number;
            /** Format: float */
            x: number;
            /** Format: float */
            y: number;
        };
        AdminFace: {
            bounds: components["schemas"]["AdminBounds"];
            crop_url: string;
            /** Format: float */
            detector_confidence: number;
            /** Format: int32 */
            embedding_dimension: number;
            embedding_model: string;
            id: string;
            /** Format: double */
            identity_score?: number | null;
            identity_state: string;
            landmark_model: string;
            landmark_schema: string;
            landmarks: components["schemas"]["AdminLandmark"][];
            /** Format: int32 */
            ordinal: number;
            person_id?: string | null;
            person_name?: string | null;
        };
        AdminFaceDashboard: {
            photos: components["schemas"]["AdminPhoto"][];
            pipeline_version: string;
            queue: components["schemas"]["AdminQueueStatus"];
            summary: components["schemas"]["AdminFaceSummary"];
        };
        AdminFaceSummary: {
            /** Format: int64 */
            analyzed_photos: number;
            /** Format: int64 */
            assigned_faces: number;
            /** Format: int64 */
            detected_faces: number;
            /** Format: int64 */
            unknown_faces: number;
        };
        AdminLandmark: {
            /** Format: float */
            x: number;
            /** Format: float */
            y: number;
            /** Format: float */
            z: number;
        };
        AdminPhoto: {
            /** Format: int64 */
            attempt_count: number;
            captured_at: string;
            faces: components["schemas"]["AdminFace"][];
            id: string;
            last_error?: string | null;
            lease_expires_at?: string | null;
            leased_by?: string | null;
            /** Format: int32 */
            oriented_height?: number | null;
            /** Format: int32 */
            oriented_width?: number | null;
            photo_url: string;
            /** Format: int64 */
            processing_millis?: number | null;
            status: string;
            thumbnail_url: string;
        };
        AdminQueueStatus: {
            /** Format: int64 */
            complete: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            leased: number;
            /** Format: int64 */
            pending: number;
        };
        AssignFaceRequest: {
            person_id?: string | null;
        };
        AssignFaceResponse: {
            face_id: string;
            identity_state: string;
            person_id?: string | null;
        };
        BatchAssignFacesRequest: {
            assignments: components["schemas"]["FaceAssignmentUpdate"][];
        };
        BatchAssignFacesResponse: {
            assignments: components["schemas"]["AssignFaceResponse"][];
        };
        /**
         * @description What a camera reports about one capture.
         *
         *     See `docs/capture-metadata.md` for units. In short: times are microseconds,
         *     gains are dimensionless multipliers, `lens_position` is dioptres, and
         *     `mean_luma` is the sensor's average luminance on a 0-255 scale.
         */
        CaptureMetadata: {
            /** @description `unknown`, `searching`, `focused` or `failed`. */
            af_state?: string | null;
            /**
             * Format: double
             * @description Analogue sensor gain as a dimensionless multiplier (1.0 = unity).
             */
            analog_gain?: number | null;
            /** @description `device`, `phone` or `legacy`. */
            capture_source?: string | null;
            /**
             * @description When the shutter fired, RFC 3339 in UTC. Preferred over the timestamp
             *     embedded in the capture ID when it is present and plausible.
             */
            captured_at?: string | null;
            /**
             * Format: int64
             * @description Estimated scene colour temperature in kelvin. Pi only today.
             */
            colour_temperature_k?: number | null;
            /**
             * Format: double
             * @description Digital gain as a dimensionless multiplier. Pi only today.
             */
            digital_gain?: number | null;
            /**
             * Format: int64
             * @description Exposure time in microseconds (libcamera `ExposureTime`).
             */
            exposure_us?: number | null;
            /**
             * @description Software version of the camera that took this photograph. When a
             *     paired device omits it, the server snapshots `devices.firmware_version`.
             */
            firmware_version?: string | null;
            /**
             * Format: int64
             * @description Autofocus sharpness score, when the AF firmware reports one.
             */
            focus_score?: number | null;
            /** Format: int64 */
            height?: number | null;
            /**
             * Format: int64
             * @description JPEG quality normalised to 0-100 on every platform.
             */
            jpeg_quality?: number | null;
            /**
             * Format: double
             * @description Lens position in dioptres (reciprocal metres). Pi/IMX519 only today.
             */
            lens_position?: number | null;
            /**
             * Format: int64
             * @description Sensor average luminance, 0-255. Low light is this project's known
             *     cause of blur, so this is the field to sort a bad batch by.
             */
            mean_luma?: number | null;
            /** @description Image sensor part, lowercase: `ov5640`, `imx519`, `imx708`. */
            sensor?: string | null;
            /** @description `button`, `debug`, `schedule` or `app`. */
            trigger?: string | null;
            /**
             * Format: int64
             * @description Encoded pixel dimensions, before any server-side rotation.
             */
            width?: number | null;
        };
        /** @description Response of `POST /api/devices/claim-tokens`. Requires a user session. */
        ClaimTokenGrant: {
            /** @description Single-use, bound to the caller's household. */
            claim_token: string;
            /** @description RFC 3339 timestamp after which the token is rejected. */
            expires_at: string;
            /** @description Origin the device should store and use for every later request. */
            server_url: string;
        };
        CreateHouseholdRequest: {
            display_name: string;
            /** Format: int32 */
            grid_size: number;
        };
        CreatePersonRequest: {
            display_name: string;
        };
        CreatePersonResponse: {
            display_name: string;
            id: string;
        };
        /**
         * @description Body of `POST /api/devices/claim`. The claim token is the credential; no
         *     other authentication is required.
         */
        DeviceClaimRequest: {
            claim_token: string;
            /**
             * @description Stable identifier generated by the device on first boot and regenerated
             *     by a full reset.
             */
            device_id: string;
            firmware_version: string;
            /** @description Free-form hardware label, e.g. `esp32-p4-imx519` or `host`. */
            hardware: string;
        };
        /** @description Response of `POST /api/devices/claim`. */
        DeviceClaimed: {
            /** @description Human-readable name assigned by the server, editable later in the app. */
            device_name: string;
            /** @description Long-lived bearer token. The device stores it and never shows it to the app. */
            device_token: string;
            household_id: string;
        };
        /**
         * @description Response of `GET /api/devices`: every device paired to the caller's
         *     household, newest claim first.
         */
        DeviceListResponse: {
            devices: components["schemas"]["DeviceSummary"][];
        };
        /** @description Summary row returned to the app for the household's devices. */
        DeviceSummary: {
            claimed_at: string;
            device_id: string;
            device_name: string;
            firmware_version: string;
            hardware: string;
            last_seen_at?: string | null;
        };
        EnrollmentPhoto: {
            captured_at: string;
            /** Format: int32 */
            face_count?: number | null;
            photo_id: string;
            /** @description `uploading`, `processing`, `enrolled`, `retake` or `failed`. */
            status: string;
            thumbnail_url?: string | null;
        };
        EnrollmentStatus: {
            enrolled: boolean;
            /** Format: int32 */
            enrolled_photos: number;
            person_id: string;
            photos: components["schemas"]["EnrollmentPhoto"][];
            /** Format: int32 */
            required_photos: number;
        };
        EnrollmentSummary: {
            enrolled: boolean;
            /** Format: int32 */
            enrolled_photos: number;
            /** Format: int32 */
            required_photos: number;
        };
        FaceAssignmentUpdate: {
            dismiss?: boolean;
            face_id: string;
            person_id?: string | null;
        };
        FlipbookFrame: {
            capture_day: string;
            captured_at: string;
            crop_url: string;
            /** Format: float */
            detector_confidence: number;
            face_id: string;
            photo_id: string;
            photo_url: string;
        };
        /**
         * @description Whether a photograph may appear in people's flipbooks. The flag lives on
         *     the photo, so it survives rotation, which discards and re-detects faces.
         */
        FlipbookMembership: {
            included: boolean;
        };
        Health: {
            /**
             * @description Applied schema version, the version this build expects, and how many
             *     migrations are still pending. `status` is `degraded` when they differ.
             */
            schema: components["schemas"]["SchemaReport"];
            software_version: string;
            status: string;
            storage_backend: string;
        };
        HouseholdConfig: {
            display_name: string;
            /** Format: int32 */
            grid_size: number;
            id: string;
            person_ids: string[];
        };
        HouseholdPerson: {
            /**
             * @description `linked` when this person has a user account, `none` otherwise. The
             *     invite flow hangs off this.
             */
            account: string;
            display_name: string;
            enrollment: components["schemas"]["EnrollmentSummary"];
            id: string;
            /**
             * @description Set when this person is linked to an account; people in the grid who
             *     have no login of their own have no role.
             */
            role?: string | null;
        };
        HouseholdSummary: {
            display_name: string;
            /** Format: int32 */
            grid_size: number;
            id: string;
            people: components["schemas"]["HouseholdPerson"][];
            /** @description The signed-in account's standing here: `admin` or `member`. */
            role: string;
            /** @description The member representing the signed-in user, when onboarding created one. */
            self_person_id?: string | null;
        };
        HouseholdsResponse: {
            households: components["schemas"]["HouseholdConfig"][];
        };
        MatchingSummary: {
            /** Format: int64 */
            examined: number;
            /** Format: int64 */
            proposed: number;
        };
        NativePasskeyChallenge: {
            ceremony_id: string;
            /** @description WebAuthn request options, including the publicKey challenge. */
            options: unknown;
        };
        NativePasskeyLoginFinish: {
            ceremony_id: string;
            credential: unknown;
        };
        NativePasskeyLoginStart: {
            /** @description Omit (or send an empty string) to let the platform pick the account. */
            username?: string | null;
        };
        NativeSession: {
            /** Format: int64 */
            expires_in_seconds: number;
            token: string;
            user: components["schemas"]["User"];
        };
        PasskeyList: {
            passkeys: components["schemas"]["PasskeySummary"][];
        };
        PasskeySummary: {
            created_at: string;
            credential_id: string;
            label: string;
            last_used_at?: string | null;
        };
        PasswordLogin: {
            password: string;
            username: string;
        };
        PeopleResponse: {
            people: components["schemas"]["PersonFlipbook"][];
        };
        PersonFlipbook: {
            /** Format: int64 */
            day_count: number;
            display_name: string;
            /** Format: int64 */
            face_count: number;
            frames: components["schemas"]["FlipbookFrame"][];
            id: string;
            last_seen_at?: string | null;
        };
        PersonPhotosResponse: {
            photo_ids: string[];
        };
        Photo: {
            capture?: null | components["schemas"]["PhotoCapture"];
            /** @description Photographs the owner has excluded from every person's flipbook. */
            flipbook_excluded?: boolean;
            id: string;
            thumbnail_url?: string | null;
            url: string;
        };
        /**
         * @description What the gallery shows about one photograph's provenance: the same fields
         *     the camera reported, plus the paired camera's name so a bad photograph
         *     names the mirror it came from.
         *
         *     Flat rather than nested so the response reads exactly like the request.
         */
        PhotoCapture: {
            af_state?: string | null;
            /** Format: double */
            analog_gain?: number | null;
            capture_source?: string | null;
            /** Format: int64 */
            colour_temperature_k?: number | null;
            device_id?: string | null;
            /** @description The name the household gave this camera when it was paired. */
            device_name?: string | null;
            /** Format: double */
            digital_gain?: number | null;
            /** Format: int64 */
            exposure_us?: number | null;
            firmware_version?: string | null;
            /** Format: int64 */
            focus_score?: number | null;
            /** Format: int64 */
            height?: number | null;
            /** Format: int64 */
            jpeg_quality?: number | null;
            /** Format: double */
            lens_position?: number | null;
            /** Format: int64 */
            mean_luma?: number | null;
            sensor?: string | null;
            trigger?: string | null;
            /** Format: int64 */
            width?: number | null;
        };
        PhotoFace: {
            /** @description Fractions of the oriented image, 0..1. */
            bounds: components["schemas"]["AdminBounds"];
            id: string;
            /** @description `confirmed`, `proposed`, or `unknown`. */
            identity_state: string;
            person_id?: string | null;
            person_name?: string | null;
        };
        /** @description Faces detected in one photograph, for drawing labels over the image. */
        PhotoFacesResponse: {
            /** @description False until the face pipeline has analyzed the current media revision. */
            analyzed: boolean;
            faces: components["schemas"]["PhotoFace"][];
            photo_id: string;
        };
        PhotoList: {
            photos: components["schemas"]["Photo"][];
        };
        ReconcileReport: {
            generated_thumbnails: number;
            imported_orphans: number;
            missing_storage_objects: number;
            ready_after: number;
            ready_before: number;
            recovered_pending: number;
            storage_objects: number;
            thumbnail_failures: number;
            unresolved_pending: number;
        };
        /** @description Renaming a household is an administrator action. */
        RenameHouseholdRequest: {
            display_name: string;
        };
        RotatePhoto: {
            /** Format: int32 */
            degrees: number;
        };
        /** @description What `/healthz` reports about the schema, and what a refused request says. */
        SchemaReport: {
            /** @description `ok`, `schema_migration_pending` or `schema_migration_drift`. */
            code: string;
            /**
             * Format: int64
             * @description The highest migration this database has recorded.
             */
            current_version: number;
            detail?: string | null;
            /**
             * Format: int64
             * @description The version this build was compiled against.
             */
            expected_version: number;
            /** @description How many of this build's migrations have not been applied. */
            pending: number;
        };
        /**
         * @description The libcamera control names `rpicam-still --metadata-format json` prints,
         *     which the Pi already writes beside each capture. Accepting this shape lets
         *     the Pi forward its sidecar unchanged; explicit `capture` fields win.
         *
         *     Unknown controls are ignored.
         */
        SensorMetadata: {
            /**
             * @description libcamera prints this as an integer enum in some builds and a name in
             *     others, so it is read loosely and normalised below.
             */
            AfState?: unknown;
            /** Format: double */
            AnalogueGain?: number | null;
            /** Format: int64 */
            ColourTemperature?: number | null;
            /** Format: double */
            DigitalGain?: number | null;
            /** Format: int64 */
            ExposureTime?: number | null;
            /** Format: double */
            LensPosition?: number | null;
        };
        SignupRequest: {
            display_name: string;
            password: string;
            username: string;
        };
        UpdateHouseholdRequest: {
            display_name: string;
            /** Format: int32 */
            grid_size: number;
            person_ids: string[];
        };
        UploadGrant: {
            complete_url: string;
            /** Format: int64 */
            expires_in_seconds?: number | null;
            headers: {
                [key: string]: string;
            };
            method: string;
            url: string;
        };
        /**
         * @description The capture a client wants to upload. Shared by the device flow and
         *     guided enrollment so both grant the same contract.
         */
        UploadRequest: {
            capture?: null | components["schemas"]["CaptureMetadata"];
            capture_id: string;
            /** Format: int64 */
            content_length: number;
            content_type: string;
            sensor_metadata?: null | components["schemas"]["SensorMetadata"];
        };
        User: {
            display_name: string;
            /** @description Set once the user completes household onboarding. */
            household_id?: string | null;
            /** @description Account-level standing in that household: `admin` or `member`. */
            household_role: string;
            id: string;
            /** @description The person record in the catalog that represents this user. */
            person_id?: string | null;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    deleteApiAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiAdminFaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFaceDashboard"];
                };
            };
        };
    };
    patchApiAdminFaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchAssignFacesRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAssignFacesResponse"];
                };
            };
        };
    };
    postApiAdminFacesSuggest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchingSummary"];
                };
            };
        };
    };
    patchApiAdminFacesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignFaceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignFaceResponse"];
                };
            };
        };
    };
    getApiAdminHouseholds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdsResponse"];
                };
            };
        };
    };
    postApiAdminHouseholds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHouseholdRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdConfig"];
                };
            };
        };
    };
    patchApiAdminHouseholdsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHouseholdRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdConfig"];
                };
            };
        };
    };
    getApiAdminPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleResponse"];
                };
            };
        };
    };
    postApiAdminPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePersonResponse"];
                };
            };
        };
    };
    getApiAdminPeopleByIdPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonPhotosResponse"];
                };
            };
        };
    };
    postApiAuthLoginNative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLogin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSession"];
                };
            };
        };
    };
    postApiAuthLoginNativePasskeyFinish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativePasskeyLoginFinish"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSession"];
                };
            };
        };
    };
    postApiAuthLoginNativePasskeyStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativePasskeyLoginStart"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativePasskeyChallenge"];
                };
            };
        };
    };
    getApiAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    getApiAuthPasskeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyList"];
                };
            };
        };
    };
    postApiAuthSignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSession"];
                };
            };
        };
    };
    getApiDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
        };
    };
    postApiDevicesClaim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceClaimRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceClaimed"];
                };
            };
        };
    };
    "postApiDevicesClaim-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimTokenGrant"];
                };
            };
        };
    };
    getApiHousehold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdSummary"];
                };
            };
        };
    };
    patchApiHousehold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameHouseholdRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdSummary"];
                };
            };
        };
    };
    postApiHouseholdPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdPerson"];
                };
            };
        };
    };
    getApiHouseholdPeopleByPerson_idEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentStatus"];
                };
            };
        };
    };
    postApiHouseholdPeopleByPerson_idEnrollmentUploads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadGrant"];
                };
            };
        };
    };
    postApiHouseholdPeopleByPerson_idEnrollmentUploadsByPhoto_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The enrollment photo was accepted for processing */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiMaintenanceProcess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getApiMaintenanceReconcile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileReport"];
                };
            };
        };
    };
    getApiPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoList"];
                };
            };
        };
    };
    deleteApiPhotosById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchApiPhotosById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotatePhoto"];
            };
        };
        responses: {
            /** @description Photo rotated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiPhotosByIdFaces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoFacesResponse"];
                };
            };
        };
    };
    putApiPhotosByIdFlipbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlipbookMembership"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlipbookMembership"];
                };
            };
        };
    };
    postApiUploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadGrant"];
                };
            };
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
