/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/faces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminFaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiAdminFaces"];
        trace?: never;
    };
    "/api/admin/faces/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAdminFacesSuggest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/faces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiAdminFacesById"];
        trace?: never;
    };
    "/api/admin/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminHouseholds"];
        put?: never;
        post: operations["postApiAdminHouseholds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/households/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchApiAdminHouseholdsById"];
        trace?: never;
    };
    "/api/admin/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminPeople"];
        put?: never;
        post: operations["postApiAdminPeople"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/people/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAdminPeopleByIdPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/native": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAuthLoginNative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/native/passkey/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAuthLoginNativePasskeyFinish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/native/passkey/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAuthLoginNativePasskeyStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiAuthPasskeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiMaintenanceProcess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiMaintenanceReconcile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteApiPhotosById"];
        options?: never;
        head?: never;
        patch: operations["patchApiPhotosById"];
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiUploads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminBounds: {
            /** Format: float */
            height: number;
            /** Format: float */
            width: number;
            /** Format: float */
            x: number;
            /** Format: float */
            y: number;
        };
        AdminFace: {
            bounds: components["schemas"]["AdminBounds"];
            crop_url: string;
            /** Format: float */
            detector_confidence: number;
            /** Format: int32 */
            embedding_dimension: number;
            embedding_model: string;
            id: string;
            /** Format: double */
            identity_score?: number | null;
            identity_state: string;
            landmark_model: string;
            landmark_schema: string;
            landmarks: components["schemas"]["AdminLandmark"][];
            /** Format: int32 */
            ordinal: number;
            person_id?: string | null;
            person_name?: string | null;
        };
        AdminFaceDashboard: {
            photos: components["schemas"]["AdminPhoto"][];
            pipeline_version: string;
            queue: components["schemas"]["AdminQueueStatus"];
            summary: components["schemas"]["AdminFaceSummary"];
        };
        AdminFaceSummary: {
            /** Format: int64 */
            analyzed_photos: number;
            /** Format: int64 */
            assigned_faces: number;
            /** Format: int64 */
            detected_faces: number;
            /** Format: int64 */
            unknown_faces: number;
        };
        AdminLandmark: {
            /** Format: float */
            x: number;
            /** Format: float */
            y: number;
            /** Format: float */
            z: number;
        };
        AdminPhoto: {
            /** Format: int64 */
            attempt_count: number;
            captured_at: string;
            faces: components["schemas"]["AdminFace"][];
            id: string;
            last_error?: string | null;
            lease_expires_at?: string | null;
            leased_by?: string | null;
            /** Format: int32 */
            oriented_height?: number | null;
            /** Format: int32 */
            oriented_width?: number | null;
            photo_url: string;
            /** Format: int64 */
            processing_millis?: number | null;
            status: string;
            thumbnail_url: string;
        };
        AdminQueueStatus: {
            /** Format: int64 */
            complete: number;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            leased: number;
            /** Format: int64 */
            pending: number;
        };
        AssignFaceRequest: {
            person_id?: string | null;
        };
        AssignFaceResponse: {
            face_id: string;
            identity_state: string;
            person_id?: string | null;
        };
        BatchAssignFacesRequest: {
            assignments: components["schemas"]["FaceAssignmentUpdate"][];
        };
        BatchAssignFacesResponse: {
            assignments: components["schemas"]["AssignFaceResponse"][];
        };
        CreateHouseholdRequest: {
            display_name: string;
            /** Format: int32 */
            grid_size: number;
        };
        CreatePersonRequest: {
            display_name: string;
        };
        CreatePersonResponse: {
            display_name: string;
            id: string;
        };
        FaceAssignmentUpdate: {
            dismiss?: boolean;
            face_id: string;
            person_id?: string | null;
        };
        FlipbookFrame: {
            capture_day: string;
            captured_at: string;
            crop_url: string;
            /** Format: float */
            detector_confidence: number;
            face_id: string;
            photo_id: string;
            photo_url: string;
        };
        Health: {
            software_version: string;
            status: string;
            storage_backend: string;
        };
        HouseholdConfig: {
            display_name: string;
            /** Format: int32 */
            grid_size: number;
            id: string;
            person_ids: string[];
        };
        HouseholdsResponse: {
            households: components["schemas"]["HouseholdConfig"][];
        };
        MatchingSummary: {
            /** Format: int64 */
            examined: number;
            /** Format: int64 */
            proposed: number;
        };
        NativePasskeyChallenge: {
            ceremony_id: string;
            /** @description WebAuthn request options, including the publicKey challenge. */
            options: unknown;
        };
        NativePasskeyLoginFinish: {
            ceremony_id: string;
            credential: unknown;
        };
        NativePasskeyLoginStart: {
            username: string;
        };
        NativeSession: {
            /** Format: int64 */
            expires_in_seconds: number;
            token: string;
            user: components["schemas"]["User"];
        };
        PasskeyList: {
            passkeys: components["schemas"]["PasskeySummary"][];
        };
        PasskeySummary: {
            created_at: string;
            credential_id: string;
            label: string;
            last_used_at?: string | null;
        };
        PasswordLogin: {
            password: string;
            username: string;
        };
        PeopleResponse: {
            people: components["schemas"]["PersonFlipbook"][];
        };
        PersonFlipbook: {
            /** Format: int64 */
            day_count: number;
            display_name: string;
            /** Format: int64 */
            face_count: number;
            frames: components["schemas"]["FlipbookFrame"][];
            id: string;
            last_seen_at?: string | null;
        };
        PersonPhotosResponse: {
            photo_ids: string[];
        };
        Photo: {
            id: string;
            thumbnail_url?: string | null;
            url: string;
        };
        PhotoList: {
            photos: components["schemas"]["Photo"][];
        };
        ReconcileReport: {
            generated_thumbnails: number;
            imported_orphans: number;
            missing_storage_objects: number;
            ready_after: number;
            ready_before: number;
            recovered_pending: number;
            storage_objects: number;
            thumbnail_failures: number;
            unresolved_pending: number;
        };
        RotatePhoto: {
            /** Format: int32 */
            degrees: number;
        };
        UpdateHouseholdRequest: {
            display_name: string;
            /** Format: int32 */
            grid_size: number;
            person_ids: string[];
        };
        UploadGrant: {
            complete_url: string;
            /** Format: int64 */
            expires_in_seconds?: number | null;
            headers: {
                [key: string]: string;
            };
            method: string;
            url: string;
        };
        UploadRequest: {
            capture_id: string;
            /** Format: int64 */
            content_length: number;
            content_type: string;
        };
        User: {
            display_name: string;
            id: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiAdminFaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFaceDashboard"];
                };
            };
        };
    };
    patchApiAdminFaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchAssignFacesRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAssignFacesResponse"];
                };
            };
        };
    };
    postApiAdminFacesSuggest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchingSummary"];
                };
            };
        };
    };
    patchApiAdminFacesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignFaceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignFaceResponse"];
                };
            };
        };
    };
    getApiAdminHouseholds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdsResponse"];
                };
            };
        };
    };
    postApiAdminHouseholds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHouseholdRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdConfig"];
                };
            };
        };
    };
    patchApiAdminHouseholdsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHouseholdRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdConfig"];
                };
            };
        };
    };
    getApiAdminPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleResponse"];
                };
            };
        };
    };
    postApiAdminPeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePersonResponse"];
                };
            };
        };
    };
    getApiAdminPeopleByIdPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonPhotosResponse"];
                };
            };
        };
    };
    postApiAuthLoginNative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLogin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSession"];
                };
            };
        };
    };
    postApiAuthLoginNativePasskeyFinish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativePasskeyLoginFinish"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSession"];
                };
            };
        };
    };
    postApiAuthLoginNativePasskeyStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativePasskeyLoginStart"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativePasskeyChallenge"];
                };
            };
        };
    };
    getApiAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    getApiAuthPasskeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyList"];
                };
            };
        };
    };
    getApiMaintenanceProcess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getApiMaintenanceReconcile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileReport"];
                };
            };
        };
    };
    getApiPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoList"];
                };
            };
        };
    };
    deleteApiPhotosById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchApiPhotosById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotatePhoto"];
            };
        };
        responses: {
            /** @description Photo rotated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postApiUploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadGrant"];
                };
            };
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
