//! Request and response models for the pairing routes, shared by the server
//! (`server/`) and the firmware. Field names are the wire format.

use serde::{Deserialize, Serialize};

/// Lifetime of a claim token minted by `POST /api/devices/claim-tokens`.
pub const CLAIM_TOKEN_TTL_SECONDS: u64 = 10 * 60;

/// Response of `POST /api/devices/claim-tokens`. Requires a user session.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct ClaimTokenGrant {
    /// Single-use, bound to the caller's household.
    pub claim_token: String,
    /// RFC 3339 timestamp after which the token is rejected.
    pub expires_at: String,
    /// Origin the device should store and use for every later request.
    pub server_url: String,
}

/// Body of `POST /api/devices/claim`. The claim token is the credential; no
/// other authentication is required.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct DeviceClaimRequest {
    /// Stable identifier generated by the device on first boot and regenerated
    /// by a full reset.
    pub device_id: String,
    pub claim_token: String,
    pub firmware_version: String,
    /// Free-form hardware label, e.g. `esp32-p4-imx519` or `host`.
    pub hardware: String,
}

/// Response of `POST /api/devices/claim`.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct DeviceClaimed {
    /// Long-lived bearer token. The device stores it and never shows it to the app.
    pub device_token: String,
    pub household_id: String,
    /// Human-readable name assigned by the server, editable later in the app.
    pub device_name: String,
}

/// What the app sends to the device over the local provisioning link, as the
/// payload of the custom provisioning endpoint. Wi-Fi credentials travel in
/// the standard provisioning `wifi_config` step, not here.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct ProvisioningPayload {
    pub server_url: String,
    pub claim_token: String,
}

/// Device-side reply on the same endpoint after the claim completes or fails.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum ProvisioningResult {
    Claimed { device_name: String },
    AwaitingConfirm,
    Failed { reason: String },
}

/// Summary row returned to the app for the household's devices.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct DeviceSummary {
    pub device_id: String,
    pub device_name: String,
    pub hardware: String,
    pub firmware_version: String,
    pub claimed_at: String,
    pub last_seen_at: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provisioning_result_uses_snake_case_tag() {
        let json = serde_json::to_string(&ProvisioningResult::AwaitingConfirm).unwrap();
        assert_eq!(json, r#"{"status":"awaiting_confirm"}"#);
        let json = serde_json::to_string(&ProvisioningResult::Claimed {
            device_name: "Hallway".into(),
        })
        .unwrap();
        assert_eq!(json, r#"{"status":"claimed","device_name":"Hallway"}"#);
    }
}
