//! Store: NVS for the small durable things, an SD card for the photo queue.
//!
//! | Thing | Where | Why |
//! | --- | --- | --- |
//! | device id | NVS `mirror/device_id` | survives OTA, regenerated by a reset |
//! | credentials + device token | NVS `mirror/*` | small, needs wear levelling |
//! | queued JPEGs | `/sdcard/pending/<id>.jpg` | megabytes; flash would wear out |
//!
//! The queue layout is the Pi's: write `.<id>.tmp`, fsync, rename to
//! `<id>.jpg`. A half-written JPEG is never visible to `pending`, so a power
//! cut mid-capture costs one photograph and nothing else.

use anyhow::Result;
use daily_mirror_core::ports::{Provisioned, QueuedCapture, Store};

/// NVS namespace. Erasing this namespace is most of a full reset.
pub const NVS_NAMESPACE: &str = "mirror";
/// Where the SD card is mounted.
pub const QUEUE_MOUNT: &str = "/sdcard";
/// Queue directory under the mount.
pub const QUEUE_DIR: &str = "/sdcard/pending";

pub struct NvsSdStore {
    // Handles held open for the life of the device: an `nvs_handle_t` and the
    // `sdmmc_card_t` the FAT VFS was mounted from.
}

impl NvsSdStore {
    /// Initialize NVS, mount the SD card, and create the queue directory.
    ///
    /// Called before anything else in `main`, because `boot` needs to know
    /// whether credentials exist before it can pick its first state.
    pub fn open() -> Result<Self> {
        // FFI: nvs_flash_init (erase and retry on
        // ESP_ERR_NVS_NO_FREE_PAGES), nvs_open(NVS_NAMESPACE, NVS_READWRITE),
        // then esp_vfs_fat_sdmmc_mount(QUEUE_MOUNT, ...) and mkdir(QUEUE_DIR).
        todo!("initialize NVS and mount the SD card at {QUEUE_MOUNT}")
    }
}

impl Store for NvsSdStore {
    type Error = anyhow::Error;

    fn device_id(&mut self) -> Result<String> {
        // Read `device_id`; if absent, mint `dm-<16 hex>` from
        // esp_fill_random and commit it before returning.
        todo!("read or mint the device id in NVS")
    }

    fn load(&mut self) -> Result<Option<Provisioned>> {
        // Absent `device_token` means unprovisioned — return None rather than
        // an error, because first boot is the normal case.
        todo!("read ssid, psk, server_url, device_token and device_name from NVS")
    }

    fn save(&mut self, _provisioned: &Provisioned) -> Result<()> {
        // Write every key, then nvs_commit once. The commit is the atomic
        // point: a power cut before it leaves the device unprovisioned, which
        // is recoverable, rather than half-provisioned, which is not.
        todo!("write the credentials and device token to NVS and commit")
    }

    fn next_capture_id(&mut self) -> Result<String> {
        // The Pi's scheme, so ids remain sortable and comparable across rigs:
        // `%Y%m%dT%H%M%SZ` plus eight hex characters. SNTP sets the clock
        // after the Wi-Fi join; before that the year reads 1970, which is ugly
        // but still sorts correctly and stays unique thanks to the suffix.
        todo!("format a capture id from the RTC and esp_random")
    }

    fn enqueue(&mut self, _capture_id: &str, _jpeg: &[u8]) -> Result<QueuedCapture> {
        todo!("write {QUEUE_DIR}/.<id>.tmp, fsync, rename to <id>.jpg")
    }

    fn read(&mut self, _capture_id: &str) -> Result<Vec<u8>> {
        // 1080p JPEGs run to a few hundred kilobytes, so this allocates from
        // PSRAM. Reject any capture id that is not alphanumeric-plus-dash
        // before touching the path.
        todo!("read the queued JPEG from {QUEUE_DIR}")
    }

    fn pending(&mut self) -> Result<Vec<QueuedCapture>> {
        // Sorted by capture id, which sorts chronologically, so the queue
        // drains oldest first.
        todo!("list {QUEUE_DIR}/*.jpg")
    }

    fn remove(&mut self, _capture_id: &str) -> Result<()> {
        // Only ever called after the server confirms the upload.
        todo!("unlink the queued JPEG")
    }

    fn erase_all(&mut self) -> Result<()> {
        // The only operation that destroys data: erase the NVS namespace,
        // delete every queued JPEG, and mint a fresh device id so the server
        // treats the next claim as an entirely new device.
        todo!("erase the {NVS_NAMESPACE} namespace and empty {QUEUE_DIR}")
    }
}
